### ISSUE TITLE
which one user:pass

### ISSUE THREAD

**Issue by charm3596k** [MInggongK/Hikvision-#4]
i dont get it which one user:pass

![Screenshot_3dasdasdd](https://github.com/MInggongK/Hikvision-/assets/120266688/c3bca4e4-7f1e-4750-b277-7a8d69e53fd6)

**Comment by MInggongK** [comment]
commit

**Comment by MInggongK** [comment]
closed #4

**Comment by MInggongK** [comment]
thanks
